WebAppPP3/Models/PUESTOS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPP3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUESTOS
    {
        public int Id_puestos { get; set; }
        public string Ubicacion { get; set; }
        public string Posicion { get; set; }
        public string Empresa { get; set; }
        public string Horario { get; set; }
        public byte[] foto { get; set; }
        public string Descripcion { get; set; }
        public double Salario { get; set; }
        public System.DateTime Fecha_Publicacion { get; set; }
        public int Id_Categoria { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}

WebAppPP3/Controllers/PUESTOSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppPP3.Models;
using PagedList;

namespace WebAppPP3.Controllers
{
    public class PUESTOSController : Controller
    {
        private Practica1Programacion3Entities db = new Practica1Programacion3Entities();
        
        // GET: PUESTOS
        public ActionResult Index(string sortOrder)
        {
           
            var pUESTOS = db.PUESTOS.Include(p => p.CATEGORIA);
            return View(pUESTOS.ToList());
        }

        // GET: PUESTOS/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PUESTOS pUESTOS = db.PUESTOS.Find(id);
            if (pUESTOS == null)
            {
                return HttpNotFound();
            }
            return View(pUESTOS);
        }
        public ActionResult Detailsusr(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PUESTOS pUESTOS = db.PUESTOS.Find(id);
            if (pUESTOS == null)
            {
                return HttpNotFound();
            }
            return View(pUESTOS);
        }

        // GET: PUESTOS/Create
        public ActionResult Create()
        {
            ViewBag.Id_Categoria = new SelectList(db.CATEGORIA, "Id_Categoria", "Descripcion");
            return View();
        }

        // POST: PUESTOS/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_puestos,Ubicacion,Posicion,Empresa,Horario,foto,Descripcion,Salario,Fecha_Publicacion,Id_Categoria")] PUESTOS pUESTOS)
        {
            if (ModelState.IsValid)
            {
                db.PUESTOS.Add(pUESTOS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id_Categoria = new SelectList(db.CATEGORIA, "Id_Categoria", "Descripcion", pUESTOS.Id_Categoria);
            return View(pUESTOS);
        }

        // GET: PUESTOS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PUESTOS pUESTOS = db.PUESTOS.Find(id);
            if (pUESTOS == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_Categoria = new SelectList(db.CATEGORIA, "Id_Categoria", "Descripcion", pUESTOS.Id_Categoria);
            return View(pUESTOS);
        }

        // POST: PUESTOS/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_puestos,Ubicacion,Posicion,Empresa,Horario,foto,Descripcion,Salario,Fecha_Publicacion,Id_Categoria")] PUESTOS pUESTOS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pUESTOS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_Categoria = new SelectList(db.CATEGORIA, "Id_Categoria", "Descripcion", pUESTOS.Id_Categoria);
            return View(pUESTOS);
        }

        // GET: PUESTOS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PUESTOS pUESTOS = db.PUESTOS.Find(id);
            if (pUESTOS == null)
            {
                return HttpNotFound();
            }
            return View(pUESTOS);
        }

        // POST: PUESTOS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PUESTOS pUESTOS = db.PUESTOS.Find(id);
            db.PUESTOS.Remove(pUESTOS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Publicaciones(bool IsChecked = false,int CantItem = 10, int getcategorias = 0, String BuscarPuestos = "")
        {
          
            var PUESTOS = db.PUESTOS;
            var dbcategoria = db.CATEGORIA;
            var dbcant = db.NumeroMaxPuestos;
            if (IsChecked == false)
            {
                CantItem = dbcant.Select(s => s.CantidadPuestos).FirstOrDefault();


            }
            else
            {
                CantItem = 1000000;
                IsChecked = false;
            }
          

            List<SelectListItem> lst = new List<SelectListItem>();

            

            lst = dbcategoria.Select(x => new SelectListItem() { Text = x.Descripcion, Value = x.Id_Categoria.ToString()}).ToList();

            lst.Add(new SelectListItem() { Text = "Todos", Value = "0" });

            lst.OrderBy(s=>s.Value);

            ViewData["getcategorias"] = lst;

           

            if (!String.IsNullOrEmpty(BuscarPuestos))
            {

                ViewBag.CantidadItem = PUESTOS.OrderByDescending(s => s.Fecha_Publicacion).Where(s => s.Posicion.Contains(BuscarPuestos)).ToList().Take(CantItem).Count();

                return View(PUESTOS.OrderByDescending(s => s.Fecha_Publicacion).Where(s => s.Posicion.Contains(BuscarPuestos)).ToList().Take(CantItem));


            }
            else if (getcategorias == 0)
            {
                ViewBag.CantidadItem = PUESTOS.OrderByDescending(s => s.Fecha_Publicacion).ToList().Take(CantItem).Count();
                return View(PUESTOS.OrderByDescending(s => s.Fecha_Publicacion).ToList().Take(CantItem));
            }
            else
            {
                ViewBag.CantidadItem = PUESTOS.OrderByDescending(s => s.Fecha_Publicacion).Where(C => C.Id_Categoria == getcategorias).ToList().Take(CantItem).Count();
                return View(PUESTOS.OrderByDescending(s => s.Fecha_Publicacion).Where(C => C.Id_Categoria == getcategorias).ToList().Take(CantItem));

            }

           

        }

        





    }
}

WebAppPP3/Views/PUESTOS/Create.cshtml
@model WebAppPP3.Models.PUESTOS

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{  
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PUESTOS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ubicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ubicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ubicacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Posicion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Posicion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Posicion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Empresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Empresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Horario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Horario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Horario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_Publicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_Publicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_Publicacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Categoria, "Id_Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Categoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppPP3/Views/PUESTOS/Delete.cshtml
@model WebAppPP3.Models.PUESTOS

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PUESTOS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Posicion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Posicion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Horario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Horario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_Publicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_Publicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CATEGORIA.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORIA.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebAppPP3/Views/PUESTOS/Details.cshtml
@model WebAppPP3.Models.PUESTOS

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PUESTOS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Posicion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Posicion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Horario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Horario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_Publicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_Publicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CATEGORIA.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORIA.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id_puestos }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebAppPP3/Views/PUESTOS/Detailsusr.cshtml
@model WebAppPP3.Models.PUESTOS

@{
    ViewBag.Title = "Detailsusr";
}

<h2>Detailsusr</h2>

<div>
    <h4>PUESTOS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Posicion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Posicion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Horario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Horario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_Publicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_Publicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CATEGORIA.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CATEGORIA.Descripcion)
        </dd>

    </dl>
</div>
<p>
   
    @Html.ActionLink("Volver Atras", "Publicaciones")
</p>

WebAppPP3/Views/PUESTOS/Edit.cshtml
@model WebAppPP3.Models.PUESTOS

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PUESTOS</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_puestos)

        <div class="form-group">
            @Html.LabelFor(model => model.Ubicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ubicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ubicacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Posicion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Posicion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Posicion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Empresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Empresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Empresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Horario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Horario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Horario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_Publicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_Publicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_Publicacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Categoria, "Id_Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Categoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppPP3/Views/PUESTOS/Index.cshtml
@model IEnumerable<WebAppPP3.Models.PUESTOS>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ubicacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Posicion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Empresa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Horario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.foto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha_Publicacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CATEGORIA.Descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ubicacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Posicion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Empresa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Horario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.foto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fecha_Publicacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CATEGORIA.Descripcion)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id_puestos }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id_puestos }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id_puestos })
        </td>
    </tr>
}

</table>

WebAppPP3/Views/PUESTOS/Publicaciones.cshtml
@model IEnumerable<WebAppPP3.Models.PUESTOS>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Publicaciones";
}

<h2>Publicaciones</h2>
@using (Html.BeginForm("Publicaciones", "PUESTOS", new { cambiar = ViewBag.IsChecked , categoria = ViewBag.getcategorias, BuscarPuestos = ViewBag.BuscarPuesto }))
{
<p>
    Buscar por posicion: @Html.TextBox("BuscarPuestos")
    @Html.DropDownList("getcategorias", ViewData["getcategorias"] as List<SelectListItem>)
    Ver Todos los Registros: @Html.CheckBox("IsChecked", new { @value = "true" })
   
    <input type="submit" value="Buscar" />

</p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ubicacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Posicion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Empresa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha_Publicacion)
        </th>
        <th>

        </th>


    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ubicacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Posicion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Empresa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_Publicacion)
            </td>
            <td>

                @Html.ActionLink("Ver Mas", "Detailsusr", new { id = item.Id_puestos })

            </td>
        </tr>
    }

</table>

<br />
<h3>Cantidad de Item Mostados : @ViewBag.CantidadItem</h3>